function [P,Z,T,rho,KS,G,VBh,VSh,VPh,VBr,VSr,VPr,VBv,VSv,VPv] = HeFESTo_read(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [P,Z,T,rho,KS,G,VBh,VSh,VPh,VBr,VSr,VPr,VBv,VSv,VPv]
%   = HeFESTo_read(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [P,Z,T,rho,KS,G,VBh,VSh,VPh,VBr,VSr,VPr,VBv,VSv,VPv]
%   = HeFESTo_read(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [P,Z,T,rho,KS,G,VBh,VSh,VPh,VBr,VSr,VPr,VBv,VSv,VPv]
%   = importfile('HeFESTo.out',2, 4142);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2015/01/28 23:00:14

%% Initialize variables.
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format string for each line of text:
formatSpec = '%6f%9f%9f%11f%11f%11f%11f%11f%11f%11f%11f%11f%11f%11f%11f%11f%11f%11f%11f%11f%11f%11f%11f%11f%11f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', '', 'WhiteSpace', '', 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', '', 'WhiteSpace', '', 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Allocate imported array to column variable names
P = dataArray{:, 1};
Z = dataArray{:, 2};
T = dataArray{:, 3};
rho = dataArray{:, 4};
KS = dataArray{:, 5};
G = dataArray{:, 6};
VBh = dataArray{:, 7};
VSh = dataArray{:, 8};
VPh = dataArray{:, 9};
VBr = dataArray{:, 10};
VSr = dataArray{:, 11};
VPr = dataArray{:, 12};
VBv = dataArray{:, 13};
VSv = dataArray{:, 14};
VPv = dataArray{:, 15};


